package catan.domain.model.game.types;

public enum GameUserActionCode {
    THROW_DICE,
    BUY_CARD,
    BUILD_SETTLEMENT,
    BUILD_CITY,
    BUILD_ROAD,
    END_TURN,
    USE_CARD_YEAR_OF_PLENTY,
    USE_CARD_MONOPOLY,
    USE_CARD_ROAD_BUILDING,
    USE_CARD_KNIGHT,
    MOVE_ROBBER,
    CHOOSE_PLAYER_TO_ROB,
    KICK_OFF_RESOURCES,
    TRADE_PORT,
    TRADE_PROPOSE
}
