package catan.domain.model.dashboard.types;

public enum LogCodeType {
    START_GAME,
    THROW_DICE,
    END_TURN,
    FINISH_GAME,
    BUILD_SETTLEMENT,
    BUILD_CITY,
    BUILD_ROAD,
    BUY_CARD,
    NEW_WIDEST_NETWORK,
    INTERRUPTED_WIDEST_NETWORK,
    NEW_SECURITY_LEADER,
    DROP_RESOURCES,
    MOVE_ROBBER,
    STEAL_RESOURCE,
    USE_CARD_KNIGHT,
    USE_CARD_ROAD_BUILDING,
    USE_CARD_MONOPOLY,
    USE_CARD_YEAR_OF_PLENTY,
    TRADE_PORT,
    TRADE_PROPOSE,
    TRADE_ACCEPT,
    TRADE_DECLINE
}